name: Tests
on: [push, pull_request]
jobs:
  build:
    name: build-keylogger
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libwebsockets-dev
      - name: Compile
        run: make
      - name: Run and terminate
        run: |
          if [ -d /dev/input ]; then
            sudo out/keylogger &
            STATE_PID=$!
            sleep 3
            sudo kill -SIGINT $STATE_PID
          else
            echo "No device"
          fi
      - name: Verify
        run: |
          ls -lh out/keylogger
          ls -lh /tmp/.keylogger.log
