name: Tests
on:
  push:
    paths:
      - "**/*"
      - "!.gitattributes"
      - "!.gitignore"
      - "!README.md"
      - "!*.gif"
      - "!*.png"
  pull_request:
    paths:
      - "**/*"
      - "!.gitattributes"
      - "!.gitignore"
      - "!README.md"
      - "!*.gif"
      - "!*.png"
jobs:
  test:
    name: test-keylogger
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libwebsockets-dev
      - name: Create udev rules
        run: |
          echo "SUBSYSTEM==\"input\", OWNER=\"$USER\", MODE=\"0660\"" | sudo tee /etc/udev/rules.d/90-keylogger.rules > /dev/null
          sudo udevadm control --reload-rules
          sudo udevadm trigger
      - name: Test
        run: |
          gcc -o nob nob.c
          ./nob test
  build:
    name: build-keylogger
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libwebsockets-dev
      - name: Compile
        run: |
          gcc -o nob nob.c
          ./nob
      - name: Run and terminate
        run: |
          if [ -d /dev/input ]; then
            out/keylogger --help
            sudo out/keylogger &
            STATE_PID=$!
            sleep 3
            sudo kill -SIGINT $STATE_PID
          else
            echo "No device"
          fi
      - name: Verify
        run: ls -lh out/keylogger
      - name: Cleanup
        run: rm -f out/keylogger out/test_*
