name: Tests
on: [push, pull_request]
jobs:
  test:
    name: test-keylogger
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libcmocka-dev libwebsockets-dev
      - name: Test
        run: make test
  build:
    name: build-keylogger-${{ matrix.target }}
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        target: [default, libwebsockets]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          if [[ "${{ matrix.target }}" == "libwebsockets" ]]; then
            sudo apt-get install -y build-essential libwebsockets-dev
          else
            sudo apt-get install -y build-essential
          fi
      - name: Compile
        run: |
          if [[ "${{ matrix.target }}" == "libwebsockets" ]]; then
            make USE_LIBWEBSOCKETS=1
          else
            make
          fi
      - name: Run and terminate
        run: |
          if [ -d /dev/input ]; then
            sudo out/keylogger &
            STATE_PID=$!
            sleep 3
            sudo kill -SIGINT $STATE_PID
          else
            echo "No device"
          fi
      - name: Verify
        run: |
          ls -lh out/keylogger
          ls -lh /tmp/.keylogger.log
